# Syntax highlighting
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

exclude:
    - LICENSE
    - README.md

# Setup
title:               Brandon Schmalz - Developer
url:                 "http://Schmalzy.github.io"
baseurl:             /

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _scss
  style:            :compressed

#Personal Info
your_name:          Brandon Schmalz
your_title:         Developer
your_img:           /www/img/me.jpg
github_feedback:    "https://github.com/Schmalzy/feedback/issues/new"
